/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_xixi_menu (void);
GtkWidget* create_xixi_ajouter (void);
GtkWidget* create_xixi_modifier (void);
GtkWidget* create_confirmation (void);
