/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_xixi_menu (void)
{
  GtkWidget *xixi_menu;
  GtkWidget *fixed1;
  GtkWidget *treeview_xixi;
  GtkWidget *xixi_recherche2;
  GtkWidget *image13;
  GtkWidget *label31;
  GtkWidget *xixi_ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *xixi_afficher;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *xixi_modifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *xixi_supprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *xixi_refresh_treeview;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label11;
  GtkWidget *xixi_radio_niv1;
  GSList *xixi_radio_niv1_group = NULL;
  GtkWidget *xixi_radio_niv2;
  GtkWidget *xixi_radio_niv3;
  GtkWidget *xixi_radio_niv4;
  GtkWidget *xixi_radio_niv5;
  GtkWidget *xixi_par_niveau;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label8;
  GtkWidget *xixi_rehcerche;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;

  xixi_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (xixi_menu), _("xixi_menu"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (xixi_menu), fixed1);

  treeview_xixi = gtk_tree_view_new ();
  gtk_widget_show (treeview_xixi);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview_xixi, 48, 120);
  gtk_widget_set_size_request (treeview_xixi, 776, 296);

  xixi_recherche2 = gtk_entry_new ();
  gtk_widget_show (xixi_recherche2);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_recherche2, 840, 424);
  gtk_widget_set_size_request (xixi_recherche2, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (xixi_recherche2), 8226);

  image13 = create_pixmap (xixi_menu, "image_2021-12-16_073323.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed1), image13, 0, 0);
  gtk_widget_set_size_request (image13, 1200, 680);

  label31 = gtk_label_new (_("\n<b><span color=\"blue\">Bienvenue a l'espace Hebergement</span></b>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed1), label31, 344, 24);
  gtk_widget_set_size_request (label31, 448, 64);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  xixi_ajouter = gtk_button_new ();
  gtk_widget_show (xixi_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_ajouter, 88, 472);
  gtk_widget_set_size_request (xixi_ajouter, 104, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (xixi_ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  xixi_afficher = gtk_button_new ();
  gtk_widget_show (xixi_afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_afficher, 264, 472);
  gtk_widget_set_size_request (xixi_afficher, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (xixi_afficher), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  xixi_modifier = gtk_button_new ();
  gtk_widget_show (xixi_modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_modifier, 448, 472);
  gtk_widget_set_size_request (xixi_modifier, 104, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (xixi_modifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  xixi_supprimer = gtk_button_new ();
  gtk_widget_show (xixi_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_supprimer, 648, 472);
  gtk_widget_set_size_request (xixi_supprimer, 120, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (xixi_supprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  xixi_refresh_treeview = gtk_button_new ();
  gtk_widget_show (xixi_refresh_treeview);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_refresh_treeview, 336, 552);
  gtk_widget_set_size_request (xixi_refresh_treeview, 136, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (xixi_refresh_treeview), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox11), label11, FALSE, FALSE, 0);

  xixi_radio_niv1 = gtk_radio_button_new_with_mnemonic (NULL, _("1 ann\303\251e"));
  gtk_widget_show (xixi_radio_niv1);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_radio_niv1, 1032, 176);
  gtk_widget_set_size_request (xixi_radio_niv1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (xixi_radio_niv1), xixi_radio_niv1_group);
  xixi_radio_niv1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (xixi_radio_niv1));

  xixi_radio_niv2 = gtk_radio_button_new_with_mnemonic (NULL, _("2 ann\303\251e"));
  gtk_widget_show (xixi_radio_niv2);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_radio_niv2, 1032, 224);
  gtk_widget_set_size_request (xixi_radio_niv2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (xixi_radio_niv2), xixi_radio_niv1_group);
  xixi_radio_niv1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (xixi_radio_niv2));

  xixi_radio_niv3 = gtk_radio_button_new_with_mnemonic (NULL, _("3 ann\303\251e"));
  gtk_widget_show (xixi_radio_niv3);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_radio_niv3, 1032, 272);
  gtk_widget_set_size_request (xixi_radio_niv3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (xixi_radio_niv3), xixi_radio_niv1_group);
  xixi_radio_niv1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (xixi_radio_niv3));

  xixi_radio_niv4 = gtk_radio_button_new_with_mnemonic (NULL, _("4 ann\303\251e"));
  gtk_widget_show (xixi_radio_niv4);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_radio_niv4, 1032, 320);
  gtk_widget_set_size_request (xixi_radio_niv4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (xixi_radio_niv4), xixi_radio_niv1_group);
  xixi_radio_niv1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (xixi_radio_niv4));

  xixi_radio_niv5 = gtk_radio_button_new_with_mnemonic (NULL, _("5 ann\303\251e"));
  gtk_widget_show (xixi_radio_niv5);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_radio_niv5, 1032, 368);
  gtk_widget_set_size_request (xixi_radio_niv5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (xixi_radio_niv5), xixi_radio_niv1_group);
  xixi_radio_niv1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (xixi_radio_niv5));

  xixi_par_niveau = gtk_button_new ();
  gtk_widget_show (xixi_par_niveau);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_par_niveau, 832, 208);
  gtk_widget_set_size_request (xixi_par_niveau, 184, 72);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (xixi_par_niveau), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("les etudiant par niveau"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox8), label8, FALSE, FALSE, 0);

  xixi_rehcerche = gtk_button_new ();
  gtk_widget_show (xixi_rehcerche);
  gtk_fixed_put (GTK_FIXED (fixed1), xixi_rehcerche, 864, 472);
  gtk_widget_set_size_request (xixi_rehcerche, 120, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (xixi_rehcerche), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_xixi, "row_activated",
                    G_CALLBACK (on_treeview_xixi_row_activated),
                    NULL);
  g_signal_connect ((gpointer) xixi_ajouter, "clicked",
                    G_CALLBACK (on_xixi_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_afficher, "clicked",
                    G_CALLBACK (on_xixi_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_modifier, "clicked",
                    G_CALLBACK (on_xixi_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_supprimer, "clicked",
                    G_CALLBACK (on_xixi_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_refresh_treeview, "clicked",
                    G_CALLBACK (on_xixi_refresh_treeview_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_radio_niv1, "toggled",
                    G_CALLBACK (on_xixi_radio_niv1_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_radio_niv2, "toggled",
                    G_CALLBACK (on_xixi_radio_niv2_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_radio_niv3, "toggled",
                    G_CALLBACK (on_xixi_radio_niv3_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_radio_niv4, "toggled",
                    G_CALLBACK (on_xixi_radio_niv4_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_radio_niv5, "toggled",
                    G_CALLBACK (on_xixi_radio_niv5_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_par_niveau, "clicked",
                    G_CALLBACK (on_xixi_par_niveau_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_rehcerche, "clicked",
                    G_CALLBACK (on_xixi_rehcerche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (xixi_menu, xixi_menu, "xixi_menu");
  GLADE_HOOKUP_OBJECT (xixi_menu, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (xixi_menu, treeview_xixi, "treeview_xixi");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_recherche2, "xixi_recherche2");
  GLADE_HOOKUP_OBJECT (xixi_menu, image13, "image13");
  GLADE_HOOKUP_OBJECT (xixi_menu, label31, "label31");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_ajouter, "xixi_ajouter");
  GLADE_HOOKUP_OBJECT (xixi_menu, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (xixi_menu, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (xixi_menu, image1, "image1");
  GLADE_HOOKUP_OBJECT (xixi_menu, label1, "label1");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_afficher, "xixi_afficher");
  GLADE_HOOKUP_OBJECT (xixi_menu, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (xixi_menu, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (xixi_menu, image5, "image5");
  GLADE_HOOKUP_OBJECT (xixi_menu, label5, "label5");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_modifier, "xixi_modifier");
  GLADE_HOOKUP_OBJECT (xixi_menu, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (xixi_menu, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (xixi_menu, image2, "image2");
  GLADE_HOOKUP_OBJECT (xixi_menu, label2, "label2");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_supprimer, "xixi_supprimer");
  GLADE_HOOKUP_OBJECT (xixi_menu, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (xixi_menu, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (xixi_menu, image3, "image3");
  GLADE_HOOKUP_OBJECT (xixi_menu, label3, "label3");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_refresh_treeview, "xixi_refresh_treeview");
  GLADE_HOOKUP_OBJECT (xixi_menu, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (xixi_menu, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (xixi_menu, image11, "image11");
  GLADE_HOOKUP_OBJECT (xixi_menu, label11, "label11");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_radio_niv1, "xixi_radio_niv1");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_radio_niv2, "xixi_radio_niv2");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_radio_niv3, "xixi_radio_niv3");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_radio_niv4, "xixi_radio_niv4");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_radio_niv5, "xixi_radio_niv5");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_par_niveau, "xixi_par_niveau");
  GLADE_HOOKUP_OBJECT (xixi_menu, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (xixi_menu, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (xixi_menu, image8, "image8");
  GLADE_HOOKUP_OBJECT (xixi_menu, label8, "label8");
  GLADE_HOOKUP_OBJECT (xixi_menu, xixi_rehcerche, "xixi_rehcerche");
  GLADE_HOOKUP_OBJECT (xixi_menu, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (xixi_menu, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (xixi_menu, image4, "image4");
  GLADE_HOOKUP_OBJECT (xixi_menu, label4, "label4");

  return xixi_menu;
}

GtkWidget*
create_xixi_ajouter (void)
{
  GtkWidget *xixi_ajouter;
  GtkWidget *fixed2;
  GtkWidget *xixi_cin;
  GtkWidget *xixi_nom;
  GtkWidget *xixi_prenom;
  GtkObject *spinbutton_xixi_jour_adj;
  GtkWidget *spinbutton_xixi_jour;
  GtkObject *spinbutton_xixi_mois_adj;
  GtkWidget *spinbutton_xixi_mois;
  GtkObject *spinbutton_xixi_annee_adj;
  GtkWidget *spinbutton_xixi_annee;
  GtkWidget *xixi_numero;
  GtkWidget *xixi_retour_menu;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *xixi_valider_ajout;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *combobox_xixi_bloc;
  GtkWidget *label26;
  GtkWidget *label25;
  GtkWidget *label28;
  GtkWidget *combobox_xixi_classe;
  GtkWidget *xixi_check_femme;
  GtkWidget *xixi_check_homme;
  GtkWidget *xixi_check_double;
  GtkWidget *xixi_check_triple;
  GtkWidget *label20sssdsd;
  GtkWidget *label32;
  GtkWidget *label27;
  GtkWidget *label24;

  xixi_ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (xixi_ajouter), _("xixi_ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (xixi_ajouter), fixed2);

  xixi_cin = gtk_entry_new ();
  gtk_widget_show (xixi_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_cin, 160, 72);
  gtk_widget_set_size_request (xixi_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (xixi_cin), 8226);

  xixi_nom = gtk_entry_new ();
  gtk_widget_show (xixi_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_nom, 160, 128);
  gtk_widget_set_size_request (xixi_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (xixi_nom), 8226);

  xixi_prenom = gtk_entry_new ();
  gtk_widget_show (xixi_prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_prenom, 160, 184);
  gtk_widget_set_size_request (xixi_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (xixi_prenom), 8226);

  spinbutton_xixi_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_xixi_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_xixi_jour_adj), 1, 0);
  gtk_widget_show (spinbutton_xixi_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_xixi_jour, 144, 312);
  gtk_widget_set_size_request (spinbutton_xixi_jour, 48, 32);

  spinbutton_xixi_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_xixi_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_xixi_mois_adj), 1, 0);
  gtk_widget_show (spinbutton_xixi_mois);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_xixi_mois, 224, 312);
  gtk_widget_set_size_request (spinbutton_xixi_mois, 56, 32);

  spinbutton_xixi_annee_adj = gtk_adjustment_new (1, 2003, 1990, 1, 10, 10);
  spinbutton_xixi_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_xixi_annee_adj), 1, 0);
  gtk_widget_show (spinbutton_xixi_annee);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_xixi_annee, 328, 312);
  gtk_widget_set_size_request (spinbutton_xixi_annee, 88, 32);

  xixi_numero = gtk_entry_new ();
  gtk_widget_show (xixi_numero);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_numero, 168, 528);
  gtk_widget_set_size_request (xixi_numero, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (xixi_numero), 8226);

  xixi_retour_menu = gtk_button_new ();
  gtk_widget_show (xixi_retour_menu);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_retour_menu, 24, 16);
  gtk_widget_set_size_request (xixi_retour_menu, 88, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (xixi_retour_menu), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Accueil"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  xixi_valider_ajout = gtk_button_new ();
  gtk_widget_show (xixi_valider_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_valider_ajout, 352, 584);
  gtk_widget_set_size_request (xixi_valider_ajout, 152, 64);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (xixi_valider_ajout), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("nom"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 64, 136);
  gtk_widget_set_size_request (label21, 49, 17);

  label22 = gtk_label_new (_("prenom"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 64, 192);
  gtk_widget_set_size_request (label22, 49, 17);

  combobox_xixi_bloc = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_xixi_bloc);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_xixi_bloc, 168, 368);
  gtk_widget_set_size_request (combobox_xixi_bloc, 120, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_bloc), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_bloc), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_bloc), _("C"));

  label26 = gtk_label_new (_("type chambre"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed2), label26, 24, 424);
  gtk_widget_set_size_request (label26, 96, 32);

  label25 = gtk_label_new (_("block"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed2), label25, 64, 384);
  gtk_widget_set_size_request (label25, 40, 17);

  label28 = gtk_label_new (_("telephone"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed2), label28, 56, 536);
  gtk_widget_set_size_request (label28, 88, 24);

  combobox_xixi_classe = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_xixi_classe);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_xixi_classe, 168, 464);
  gtk_widget_set_size_request (combobox_xixi_classe, 120, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe), _("5"));

  xixi_check_femme = gtk_check_button_new_with_mnemonic (_("Femme"));
  gtk_widget_show (xixi_check_femme);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_check_femme, 296, 264);
  gtk_widget_set_size_request (xixi_check_femme, 118, 24);

  xixi_check_homme = gtk_check_button_new_with_mnemonic (_("Homme"));
  gtk_widget_show (xixi_check_homme);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_check_homme, 144, 264);
  gtk_widget_set_size_request (xixi_check_homme, 118, 24);

  xixi_check_double = gtk_check_button_new_with_mnemonic (_("Double"));
  gtk_widget_show (xixi_check_double);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_check_double, 144, 432);
  gtk_widget_set_size_request (xixi_check_double, 118, 24);

  xixi_check_triple = gtk_check_button_new_with_mnemonic (_("Triple"));
  gtk_widget_show (xixi_check_triple);
  gtk_fixed_put (GTK_FIXED (fixed2), xixi_check_triple, 296, 432);
  gtk_widget_set_size_request (xixi_check_triple, 118, 24);

  label20sssdsd = gtk_label_new (_("cin"));
  gtk_widget_show (label20sssdsd);
  gtk_fixed_put (GTK_FIXED (fixed2), label20sssdsd, 56, 72);
  gtk_widget_set_size_request (label20sssdsd, 72, 24);

  label32 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed2), label32, 56, 264);
  gtk_widget_set_size_request (label32, 49, 17);

  label27 = gtk_label_new (_("niveau"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed2), label27, 64, 480);
  gtk_widget_set_size_request (label27, 49, 17);

  label24 = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 8, 312);
  gtk_widget_set_size_request (label24, 128, 32);

  g_signal_connect ((gpointer) xixi_retour_menu, "clicked",
                    G_CALLBACK (on_xixi_retour_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_valider_ajout, "clicked",
                    G_CALLBACK (on_xixi_valider_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_check_femme, "toggled",
                    G_CALLBACK (on_xixi_check_femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_check_homme, "toggled",
                    G_CALLBACK (on_xixi_check_homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_check_double, "toggled",
                    G_CALLBACK (on_xixi_check_double_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_check_triple, "toggled",
                    G_CALLBACK (on_xixi_check_triple_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (xixi_ajouter, xixi_ajouter, "xixi_ajouter");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_cin, "xixi_cin");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_nom, "xixi_nom");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_prenom, "xixi_prenom");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, spinbutton_xixi_jour, "spinbutton_xixi_jour");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, spinbutton_xixi_mois, "spinbutton_xixi_mois");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, spinbutton_xixi_annee, "spinbutton_xixi_annee");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_numero, "xixi_numero");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_retour_menu, "xixi_retour_menu");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, image7, "image7");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label7, "label7");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_valider_ajout, "xixi_valider_ajout");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, image6, "image6");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label6, "label6");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label21, "label21");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label22, "label22");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, combobox_xixi_bloc, "combobox_xixi_bloc");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label26, "label26");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label25, "label25");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label28, "label28");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, combobox_xixi_classe, "combobox_xixi_classe");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_check_femme, "xixi_check_femme");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_check_homme, "xixi_check_homme");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_check_double, "xixi_check_double");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, xixi_check_triple, "xixi_check_triple");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label20sssdsd, "label20sssdsd");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label32, "label32");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label27, "label27");
  GLADE_HOOKUP_OBJECT (xixi_ajouter, label24, "label24");

  return xixi_ajouter;
}

GtkWidget*
create_xixi_modifier (void)
{
  GtkWidget *xixi_modifier;
  GtkWidget *fixed3;
  GtkWidget *xixi_nom1;
  GtkWidget *xixi_prenom1;
  GtkObject *spinbutton_xixi_jour1_adj;
  GtkWidget *spinbutton_xixi_jour1;
  GtkObject *spinbutton_xixi_mois1_adj;
  GtkWidget *spinbutton_xixi_mois1;
  GtkObject *spinbutton_xixi_annee1_adj;
  GtkWidget *spinbutton_xixi_annee1;
  GtkWidget *xixi_retour_menu1;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label9;
  GtkWidget *xixi_numero1;
  GtkWidget *xixi_valider_mofiier;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label10;
  GtkWidget *combobox_xixi_bloc1;
  GtkWidget *label13dvdvsdvdsv;
  GtkWidget *sfvsvds;
  GtkWidget *label19ssdsdzdzd;
  GtkWidget *label16eedef;
  GtkWidget *combobox_xixi_classe1;
  GtkWidget *xixi_check_homme1;
  GtkWidget *xixi_check_femme1;
  GtkWidget *xixi_check_double1;
  GtkWidget *xixi_check_triple1;
  GtkWidget *label15dvdvdvd;
  GtkWidget *label33;
  GtkWidget *label18dsvscs;
  GtkWidget *label17fsvfsvsv;

  xixi_modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (xixi_modifier), _("xixi_modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (xixi_modifier), fixed3);

  xixi_nom1 = gtk_entry_new ();
  gtk_widget_show (xixi_nom1);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_nom1, 192, 128);
  gtk_widget_set_size_request (xixi_nom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (xixi_nom1), 8226);

  xixi_prenom1 = gtk_entry_new ();
  gtk_widget_show (xixi_prenom1);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_prenom1, 192, 184);
  gtk_widget_set_size_request (xixi_prenom1, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (xixi_prenom1), 8226);

  spinbutton_xixi_jour1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_xixi_jour1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_xixi_jour1_adj), 1, 0);
  gtk_widget_show (spinbutton_xixi_jour1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_xixi_jour1, 160, 296);
  gtk_widget_set_size_request (spinbutton_xixi_jour1, 64, 32);

  spinbutton_xixi_mois1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_xixi_mois1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_xixi_mois1_adj), 1, 0);
  gtk_widget_show (spinbutton_xixi_mois1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_xixi_mois1, 272, 296);
  gtk_widget_set_size_request (spinbutton_xixi_mois1, 64, 32);

  spinbutton_xixi_annee1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_xixi_annee1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_xixi_annee1_adj), 1, 0);
  gtk_widget_show (spinbutton_xixi_annee1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_xixi_annee1, 376, 296);
  gtk_widget_set_size_request (spinbutton_xixi_annee1, 80, 32);

  xixi_retour_menu1 = gtk_button_new ();
  gtk_widget_show (xixi_retour_menu1);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_retour_menu1, 48, 16);
  gtk_widget_set_size_request (xixi_retour_menu1, 80, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (xixi_retour_menu1), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Accueil"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox9), label9, FALSE, FALSE, 0);

  xixi_numero1 = gtk_entry_new ();
  gtk_widget_show (xixi_numero1);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_numero1, 208, 520);
  gtk_widget_set_size_request (xixi_numero1, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (xixi_numero1), 8226);

  xixi_valider_mofiier = gtk_button_new ();
  gtk_widget_show (xixi_valider_mofiier);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_valider_mofiier, 504, 592);
  gtk_widget_set_size_request (xixi_valider_mofiier, 184, 64);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (xixi_valider_mofiier), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox10), label10, FALSE, FALSE, 0);

  combobox_xixi_bloc1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_xixi_bloc1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox_xixi_bloc1, 224, 352);
  gtk_widget_set_size_request (combobox_xixi_bloc1, 104, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_bloc1), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_bloc1), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_bloc1), _("C"));

  label13dvdvsdvdsv = gtk_label_new (_("nom"));
  gtk_widget_show (label13dvdvsdvdsv);
  gtk_fixed_put (GTK_FIXED (fixed3), label13dvdvsdvdsv, 104, 128);
  gtk_widget_set_size_request (label13dvdvsdvdsv, 49, 17);

  sfvsvds = gtk_label_new (_("prenom"));
  gtk_widget_show (sfvsvds);
  gtk_fixed_put (GTK_FIXED (fixed3), sfvsvds, 104, 192);
  gtk_widget_set_size_request (sfvsvds, 64, 24);

  label19ssdsdzdzd = gtk_label_new (_("telephone"));
  gtk_widget_show (label19ssdsdzdzd);
  gtk_fixed_put (GTK_FIXED (fixed3), label19ssdsdzdzd, 72, 520);
  gtk_widget_set_size_request (label19ssdsdzdzd, 96, 32);

  label16eedef = gtk_label_new (_("block"));
  gtk_widget_show (label16eedef);
  gtk_fixed_put (GTK_FIXED (fixed3), label16eedef, 48, 360);
  gtk_widget_set_size_request (label16eedef, 72, 17);

  combobox_xixi_classe1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_xixi_classe1);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox_xixi_classe1, 232, 456);
  gtk_widget_set_size_request (combobox_xixi_classe1, 104, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_xixi_classe1), _("5"));

  xixi_check_homme1 = gtk_check_button_new_with_mnemonic (_("Homme"));
  gtk_widget_show (xixi_check_homme1);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_check_homme1, 160, 248);
  gtk_widget_set_size_request (xixi_check_homme1, 118, 24);

  xixi_check_femme1 = gtk_check_button_new_with_mnemonic (_("Femme"));
  gtk_widget_show (xixi_check_femme1);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_check_femme1, 328, 248);
  gtk_widget_set_size_request (xixi_check_femme1, 118, 24);

  xixi_check_double1 = gtk_check_button_new_with_mnemonic (_("Double"));
  gtk_widget_show (xixi_check_double1);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_check_double1, 168, 416);
  gtk_widget_set_size_request (xixi_check_double1, 118, 24);

  xixi_check_triple1 = gtk_check_button_new_with_mnemonic (_("Triple"));
  gtk_widget_show (xixi_check_triple1);
  gtk_fixed_put (GTK_FIXED (fixed3), xixi_check_triple1, 336, 416);
  gtk_widget_set_size_request (xixi_check_triple1, 118, 24);

  label15dvdvdvd = gtk_label_new (_("date de naissance"));
  gtk_widget_show (label15dvdvdvd);
  gtk_fixed_put (GTK_FIXED (fixed3), label15dvdvdvd, 8, 304);
  gtk_widget_set_size_request (label15dvdvdvd, 128, 24);

  label33 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed3), label33, 64, 248);
  gtk_widget_set_size_request (label33, 49, 17);

  label18dsvscs = gtk_label_new (_("niveau"));
  gtk_widget_show (label18dsvscs);
  gtk_fixed_put (GTK_FIXED (fixed3), label18dsvscs, 80, 464);
  gtk_widget_set_size_request (label18dsvscs, 72, 24);

  label17fsvfsvsv = gtk_label_new (_("type chambre"));
  gtk_widget_show (label17fsvfsvsv);
  gtk_fixed_put (GTK_FIXED (fixed3), label17fsvfsvsv, 40, 416);
  gtk_widget_set_size_request (label17fsvfsvsv, 96, 32);

  g_signal_connect ((gpointer) xixi_retour_menu1, "clicked",
                    G_CALLBACK (on_xixi_retour_menu1_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_valider_mofiier, "clicked",
                    G_CALLBACK (on_xixi_valider_mofiier_clicked),
                    NULL);
  g_signal_connect ((gpointer) xixi_check_homme1, "toggled",
                    G_CALLBACK (on_xixi_check_homme1_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_check_femme1, "toggled",
                    G_CALLBACK (on_xixi_check_femme1_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_check_double1, "toggled",
                    G_CALLBACK (on_xixi_check_double1_toggled),
                    NULL);
  g_signal_connect ((gpointer) xixi_check_triple1, "toggled",
                    G_CALLBACK (on_xixi_check_triple1_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (xixi_modifier, xixi_modifier, "xixi_modifier");
  GLADE_HOOKUP_OBJECT (xixi_modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_nom1, "xixi_nom1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_prenom1, "xixi_prenom1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, spinbutton_xixi_jour1, "spinbutton_xixi_jour1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, spinbutton_xixi_mois1, "spinbutton_xixi_mois1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, spinbutton_xixi_annee1, "spinbutton_xixi_annee1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_retour_menu1, "xixi_retour_menu1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (xixi_modifier, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (xixi_modifier, image9, "image9");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label9, "label9");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_numero1, "xixi_numero1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_valider_mofiier, "xixi_valider_mofiier");
  GLADE_HOOKUP_OBJECT (xixi_modifier, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (xixi_modifier, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (xixi_modifier, image10, "image10");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label10, "label10");
  GLADE_HOOKUP_OBJECT (xixi_modifier, combobox_xixi_bloc1, "combobox_xixi_bloc1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label13dvdvsdvdsv, "label13dvdvsdvdsv");
  GLADE_HOOKUP_OBJECT (xixi_modifier, sfvsvds, "sfvsvds");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label19ssdsdzdzd, "label19ssdsdzdzd");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label16eedef, "label16eedef");
  GLADE_HOOKUP_OBJECT (xixi_modifier, combobox_xixi_classe1, "combobox_xixi_classe1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_check_homme1, "xixi_check_homme1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_check_femme1, "xixi_check_femme1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_check_double1, "xixi_check_double1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, xixi_check_triple1, "xixi_check_triple1");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label15dvdvdvd, "label15dvdvdvd");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label33, "label33");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label18dsvscs, "label18dsvscs");
  GLADE_HOOKUP_OBJECT (xixi_modifier, label17fsvfsvsv, "label17fsvfsvsv");

  return xixi_modifier;
}

GtkWidget*
create_confirmation (void)
{
  GtkWidget *confirmation;
  GtkWidget *fixed4;
  GtkWidget *xixi_confirmation;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label30;
  GtkWidget *label29;

  confirmation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (confirmation), _("confirmation"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (confirmation), fixed4);

  xixi_confirmation = gtk_button_new ();
  gtk_widget_show (xixi_confirmation);
  gtk_fixed_put (GTK_FIXED (fixed4), xixi_confirmation, 304, 256);
  gtk_widget_set_size_request (xixi_confirmation, 98, 45);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (xixi_confirmation), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox12), label30, FALSE, FALSE, 0);

  label29 = gtk_label_new (_("<b><span color=\"black\">Etudiants Enregistrer avec succes</span></b>\n"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 64, 48);
  gtk_widget_set_size_request (label29, 288, 160);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  g_signal_connect ((gpointer) xixi_confirmation, "clicked",
                    G_CALLBACK (on_xixi_confirmation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirmation, confirmation, "confirmation");
  GLADE_HOOKUP_OBJECT (confirmation, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (confirmation, xixi_confirmation, "xixi_confirmation");
  GLADE_HOOKUP_OBJECT (confirmation, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (confirmation, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (confirmation, image12, "image12");
  GLADE_HOOKUP_OBJECT (confirmation, label30, "label30");
  GLADE_HOOKUP_OBJECT (confirmation, label29, "label29");

  return confirmation;
}

